tasks:
  - init: npm ci
    command: >
      gp await 3000 &&
      gp preview $(gp url 3000) &&
      npm start

ports:
  - port: 3000
    onOpen: ignore

github:
  prebuilds:
    addComment: true
    addBadge: true
